// <auto-generated />
using DAL.Veh;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Veh.Migrations
{
    [DbContext(typeof(VehDbContext))]
    partial class VehDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DAL.Veh.Model.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Veh_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Company_name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("Varchar(20)");

                    b.Property<decimal>("GST")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<decimal>("LocalTax")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<decimal>("RoadPrice")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<string>("Seating_capacity")
                        .IsRequired()
                        .HasColumnType("Varchar(10)");

                    b.Property<decimal>("ShowroomPrice")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<string>("Veh_model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("Varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Vehicle_Catalog");
                });
#pragma warning restore 612, 618
        }
    }
}
